log_type all
log_dest stdout

listener 8883
protocol mqtt

cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key

require_certificate false
allow_anonymous false
password_file /mosquitto/config/passwd

listener 9001
protocol websockets
